"""Build a static index page over a folder of curated reports.

The CLI emits one self-contained HTML report per run. To put a curated
set of those reports on the public internet, drop them in
`docs/reports/` and run `python -m news_lens.publish build docs/`. This
walks the reports, extracts each report's metadata (title, generated
date, article / outlet / claim counts, the first topline bullet as a
description) and writes `docs/index.html` — a landing page with one
card per report, sorted newest-first.

The intent is **editorial curation, not automation**: you decide which
reports go public, when, and how they're framed. The accompanying
`.github/workflows/publish.yml` deploys whatever is in `docs/` to
GitHub Pages.

Run `python -m news_lens.publish --help` for the CLI surface.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional


@dataclass
class ReportMetadata:
    """What the index page shows about one report."""

    filename: str
    title: str
    description: str
    generated: Optional[datetime]
    n_articles: int
    n_outlets: int
    n_claims: int
    has_omissions: bool


_META_LINE_RE = re.compile(
    r'<div class="meta">'
    r"(?P<n_articles>\d+)\s+articles?"
    r".*?(?P<n_outlets>\d+)\s+outlets?"
    r".*?(?P<n_claims>\d+)\s+canonical\s+claims?"
    r".*?generated\s+(?P<generated>[\d:\s\-UTC]+)"
    r"</div>",
    re.IGNORECASE | re.DOTALL,
)
_OG_TITLE_RE = re.compile(
    r'<meta\s+property="og:title"\s+content="([^"]+)"', re.IGNORECASE
)
_OG_DESC_RE = re.compile(
    r'<meta\s+property="og:description"\s+content="([^"]+)"', re.IGNORECASE
)
_OMISSIONS_RE = re.compile(r'id="omissions"', re.IGNORECASE)


def _esc(value: str) -> str:
    return html.escape(value or "", quote=True)


def _parse_generated(stamp: str) -> Optional[datetime]:
    stamp = stamp.strip().replace(" UTC", "").strip()
    for fmt in ("%Y-%m-%d %H:%M", "%Y-%m-%d"):
        try:
            return datetime.strptime(stamp, fmt)
        except ValueError:
            continue
    return None


def extract_metadata(html_path: Path) -> Optional[ReportMetadata]:
    """Read a rendered report and pull out the fields the index needs.

    Returns None if the file doesn't look like a News Lens report
    (no meta line found). Permissive on the title/description: a report
    rendered before OG tags were added still parses; it just gets a
    fallback label.
    """
    try:
        text = html_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    meta_match = _META_LINE_RE.search(text)
    if not meta_match:
        return None

    n_articles = int(meta_match["n_articles"])
    n_outlets = int(meta_match["n_outlets"])
    n_claims = int(meta_match["n_claims"])
    generated = _parse_generated(meta_match["generated"])

    og_title_match = _OG_TITLE_RE.search(text)
    title = (
        og_title_match.group(1)
        if og_title_match
        else html_path.stem.replace("_", " ").replace("-", " ").title()
    )

    og_desc_match = _OG_DESC_RE.search(text)
    description = og_desc_match.group(1) if og_desc_match else ""

    return ReportMetadata(
        filename=html_path.name,
        title=title,
        description=description,
        generated=generated,
        n_articles=n_articles,
        n_outlets=n_outlets,
        n_claims=n_claims,
        has_omissions=bool(_OMISSIONS_RE.search(text)),
    )


_INDEX_HERO = """\
<header class="hero">
  <h1>News Lens</h1>
  <p class="lede">
    Cross-outlet coverage matrices for individual news stories. Each report
    shows how multiple outlets covered the same event side-by-side: who
    asserted what as fact, who quoted whom, which framings echoed and which
    diverged, and what was structurally absent from every article in the
    sample.
  </p>
  <p class="lede sub">
    The reports are tools for reading, not verdicts. They make the shape
    of coverage legible; the judgment is yours.
  </p>
</header>
"""

_INDEX_FOOTER = """\
<footer class="site">
  <p>
    Reports generated by <a href="https://github.com/xavimurtagh/news"
    target="_blank" rel="noopener">News Lens</a>, an open-source tool for
    cross-outlet news comparison. Curated; not automated.
  </p>
</footer>
"""

_INDEX_CSS = """\
:root {
  --bg: #fafaf7;
  --surface: #ffffff;
  --border: #e5e5e0;
  --border-strong: #c7c7be;
  --text: #1a1a1a;
  --text-muted: #6b6b66;
  --text-subtle: #9a9a93;
  --accent: #1f3a5f;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  font-size: 16px;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}
.page { max-width: 1000px; margin: 0 auto; padding: 40px 24px 64px; }

header.hero { margin-bottom: 36px; }
header.hero h1 {
  font-family: Georgia, "Times New Roman", serif;
  font-size: 36px;
  font-weight: 600;
  letter-spacing: -0.01em;
  margin: 0 0 12px;
}
header.hero .lede {
  font-family: Georgia, "Times New Roman", serif;
  font-size: 18px;
  color: var(--text);
  margin: 0 0 12px;
  max-width: 64ch;
}
header.hero .lede.sub {
  font-size: 15px;
  color: var(--text-muted);
}

.filter-bar {
  display: flex;
  gap: 12px;
  align-items: center;
  margin-bottom: 20px;
  flex-wrap: wrap;
}
.filter-bar input[type="search"] {
  flex: 1 1 240px;
  font: inherit;
  padding: 8px 12px;
  border: 1px solid var(--border-strong);
  border-radius: 6px;
  background: var(--surface);
}
.filter-bar input[type="search"]:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}
.filter-bar .count {
  font-size: 13px;
  color: var(--text-muted);
}

.reports {
  display: grid;
  gap: 16px;
  grid-template-columns: 1fr;
}
@media (min-width: 720px) {
  .reports { grid-template-columns: 1fr 1fr; }
}

.report-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 18px 20px;
  transition: border-color 120ms ease, transform 120ms ease;
}
.report-card:hover {
  border-color: var(--accent);
  transform: translateY(-1px);
}
.report-card a {
  color: inherit;
  text-decoration: none;
  display: block;
}
.report-card a:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 4px;
  border-radius: 8px;
}
.report-card h2 {
  font-family: Georgia, "Times New Roman", serif;
  font-size: 18px;
  font-weight: 600;
  margin: 0 0 8px;
  line-height: 1.3;
}
.report-card .desc {
  font-size: 14px;
  color: var(--text-muted);
  line-height: 1.5;
  margin: 0 0 14px;
}
.report-card .stats {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
  font-size: 12px;
  color: var(--text-subtle);
}
.report-card .stat {
  background: #f4f4ef;
  padding: 2px 8px;
  border-radius: 10px;
}
.report-card .date {
  font-size: 12px;
  color: var(--text-subtle);
  font-variant-numeric: tabular-nums;
  margin-top: 8px;
}

footer.site {
  margin-top: 48px;
  padding-top: 18px;
  border-top: 1px solid var(--border);
  font-size: 13px;
  color: var(--text-subtle);
}
footer.site a { color: var(--accent); }

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a18;
    --surface: #232320;
    --border: #3a3a35;
    --border-strong: #4d4d47;
    --text: #ededeb;
    --text-muted: #b0b0a8;
    --text-subtle: #828278;
    --accent: #7aa3d8;
  }
  .report-card .stat { background: #2a2a26; }
}

/* Filter-hide rule used by the inline search. */
.report-card[hidden] { display: none; }
"""

_INDEX_FILTER_JS = """\
<script>
(function() {
  var input = document.getElementById('q');
  var cards = Array.prototype.slice.call(document.querySelectorAll('.report-card'));
  var count = document.getElementById('count');
  function refresh() {
    var q = (input.value || '').toLowerCase().trim();
    var shown = 0;
    cards.forEach(function(c) {
      var hay = (c.getAttribute('data-search') || '').toLowerCase();
      var match = !q || hay.indexOf(q) !== -1;
      c.hidden = !match;
      if (match) shown += 1;
    });
    count.textContent = shown + ' of ' + cards.length + ' reports';
  }
  if (input) input.addEventListener('input', refresh);
  refresh();
})();
</script>
"""


def _render_card(meta: ReportMetadata) -> str:
    date_label = meta.generated.strftime("%Y-%m-%d") if meta.generated else ""
    stats = [
        f"{meta.n_articles} article{'' if meta.n_articles == 1 else 's'}",
        f"{meta.n_outlets} outlet{'' if meta.n_outlets == 1 else 's'}",
        f"{meta.n_claims} claim{'' if meta.n_claims == 1 else 's'}",
    ]
    if meta.has_omissions:
        stats.append("omissions flagged")
    stats_html = "".join(f'<span class="stat">{_esc(s)}</span>' for s in stats)
    haystack = " ".join([
        meta.title, meta.description, meta.filename, date_label,
    ])
    return (
        f'<article class="report-card" data-search="{_esc(haystack)}">'
        f'<a href="reports/{_esc(meta.filename)}">'
        f'<h2>{_esc(meta.title)}</h2>'
        f'<p class="desc">{_esc(meta.description)}</p>'
        f'<div class="stats">{stats_html}</div>'
        f'<div class="date">{_esc(date_label)}</div>'
        "</a></article>"
    )


def build_index(docs_dir: Path) -> Path:
    """Walk docs_dir/reports/*.html and write docs_dir/index.html."""
    reports_dir = docs_dir / "reports"
    if not reports_dir.is_dir():
        raise SystemExit(
            f"error: {reports_dir} not found. Create it and drop your "
            "report HTML files there."
        )

    metas: list[ReportMetadata] = []
    for path in sorted(reports_dir.glob("*.html")):
        meta = extract_metadata(path)
        if meta is None:
            print(
                f"WARN: {path.name} does not look like a News Lens report; "
                "skipping.",
                file=sys.stderr,
            )
            continue
        metas.append(meta)

    metas.sort(
        key=lambda m: m.generated or datetime.min,
        reverse=True,
    )

    cards_html = "".join(_render_card(m) for m in metas)
    body = (
        _INDEX_HERO
        + '<div class="filter-bar">'
        + '<input type="search" id="q" placeholder="Filter by story, outlet, or date" '
        'aria-label="Filter reports">'
        + f'<span class="count" id="count">{len(metas)} report{"" if len(metas) == 1 else "s"}</span>'
        + "</div>"
        + f'<div class="reports">{cards_html}</div>'
        + _INDEX_FOOTER
    )

    page = (
        "<!DOCTYPE html>"
        '<html lang="en">'
        "<head>"
        '<meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        "<title>News Lens — published reports</title>"
        '<meta property="og:title" content="News Lens — published reports">'
        '<meta property="og:description" content="Cross-outlet coverage matrices for individual news stories.">'
        '<meta property="og:type" content="website">'
        f"<style>{_INDEX_CSS}</style>"
        "</head>"
        '<body><div class="page">'
        f"{body}"
        "</div>"
        f"{_INDEX_FILTER_JS}"
        "</body></html>"
    )

    out = docs_dir / "index.html"
    out.write_text(page, encoding="utf-8")
    return out


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m news_lens.publish",
        description=(
            "Build a landing page over a curated set of News Lens reports."
        ),
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    build = sub.add_parser(
        "build",
        help="Walk docs/reports/*.html and write docs/index.html.",
    )
    build.add_argument(
        "docs_dir",
        type=Path,
        help="Path to the docs/ folder containing a reports/ subfolder.",
    )

    args = parser.parse_args(argv)
    if args.cmd == "build":
        out = build_index(args.docs_dir)
        print(f"Wrote {out}", file=sys.stderr)
        return 0
    parser.error(f"unknown command: {args.cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
